// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as Max from "date-fns/fp/max";
import * as Ru from "date-fns/locale/ru";
import * as ParseISO from "date-fns/fp/parseISO";
import * as DateFns$ReasonDateFns from "./DateFns.bs.js";
import * as StartOfDay from "date-fns/fp/startOfDay";

console.log(new Date());

console.log(DateFns$ReasonDateFns.isBefore(new Date(), new Date()));

console.log(Max.default(/* array */[
          new Date(),
          new Date()
        ]));

DateFns$ReasonDateFns.lightFormat("yyyy-MM-dd", DateFns$ReasonDateFns.closestTo(/* array */[
          ParseISO.default("2019-08-21T13:00:03.058Z"),
          new Date()
        ], DateFns$ReasonDateFns.addDays(-2, DateFns$ReasonDateFns.addDays(2, new Date()))));

DateFns$ReasonDateFns.formatWithOptions({
      locale: Ru.default
    }, "yyyy-MM-dd", new Date());

console.log(DateFns$ReasonDateFns.addMilliseconds(1000, DateFns$ReasonDateFns.addSeconds(10, DateFns$ReasonDateFns.addMinutes(10, new Date()))));

console.log("test", DateFns$ReasonDateFns.setHours(7, StartOfDay.default(DateFns$ReasonDateFns.addDays(1, new Date()))));

export {
  
}
/*  Not a pure module */
