// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE


function curry2(uncurried2, a, b) {
  return uncurried2(a)(b);
}

function curry3(uncurried3, a, b, c) {
  return uncurried3(a)(b)(c);
}

export {
  curry2 ,
  curry3 ,
  
}
/* No side effect */
