// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Parse = require("date-fns/fp/parse").default;
var Format = require("date-fns/fp/format").default;
var SetDay = require("date-fns/fp/setDay").default;
var AddDays = require("date-fns/fp/addDays").default;
var IsAfter = require("date-fns/fp/isAfter").default;
var IsEqual = require("date-fns/fp/isEqual").default;
var SetWeek = require("date-fns/fp/setWeek").default;
var SetYear = require("date-fns/fp/setYear").default;
var SubDays = require("date-fns/fp/subDays").default;
var AddHours = require("date-fns/fp/addHours").default;
var AddWeeks = require("date-fns/fp/addWeeks").default;
var AddYears = require("date-fns/fp/addYears").default;
var IsBefore = require("date-fns/fp/isBefore").default;
var SetHours = require("date-fns/fp/setHours").default;
var SetMonth = require("date-fns/fp/setMonth").default;
var SubHours = require("date-fns/fp/subHours").default;
var SubWeeks = require("date-fns/fp/subWeeks").default;
var SubYears = require("date-fns/fp/subYears").default;
var AddMonths = require("date-fns/fp/addMonths").default;
var ClosestTo = require("date-fns/fp/closestTo").default;
var IsSameDay = require("date-fns/fp/isSameDay").default;
var SetISODay = require("date-fns/fp/setISODay").default;
var SubMonths = require("date-fns/fp/subMonths").default;
var AddMinutes = require("date-fns/fp/addMinutes").default;
var AddSeconds = require("date-fns/fp/addSeconds").default;
var CompareAsc = require("date-fns/fp/compareAsc").default;
var IsSameHour = require("date-fns/fp/isSameHour").default;
var IsSameWeek = require("date-fns/fp/isSameWeek").default;
var IsSameYear = require("date-fns/fp/isSameYear").default;
var SetMinutes = require("date-fns/fp/setMinutes").default;
var SetSeconds = require("date-fns/fp/setSeconds").default;
var SubMinutes = require("date-fns/fp/subMinutes").default;
var SubSeconds = require("date-fns/fp/subSeconds").default;
var CompareDesc = require("date-fns/fp/compareDesc").default;
var IsSameMonth = require("date-fns/fp/isSameMonth").default;
var LightFormat = require("date-fns/fp/lightFormat").default;
var IsSameMinute = require("date-fns/fp/isSameMinute").default;
var IsSameSecond = require("date-fns/fp/isSameSecond").default;
var SetDayOfYear = require("date-fns/fp/setDayOfYear").default;
var ClosestIndexTo = require("date-fns/fp/closestIndexTo").default;
var FormatDistance = require("date-fns/fp/formatDistance").default;
var FormatRelative = require("date-fns/fp/formatRelative").default;
var AddBusinessDays = require("date-fns/fp/addBusinessDays").default;
var AddMilliseconds = require("date-fns/fp/addMilliseconds").default;
var SetMilliseconds = require("date-fns/fp/setMilliseconds").default;
var SubMilliseconds = require("date-fns/fp/subMilliseconds").default;
var DifferenceInDays = require("date-fns/fp/differenceInDays").default;
var IsLastDayOfMonth = require("date-fns/fp/isLastDayOfMonth").default;
var DifferenceInHours = require("date-fns/fp/differenceInHours").default;
var DifferenceInWeeks = require("date-fns/fp/differenceInWeeks").default;
var DifferenceInYears = require("date-fns/fp/differenceInYears").default;
var FormatWithOptions = require("date-fns/fp/formatWithOptions").default;
var IsFirstDayOfMonth = require("date-fns/fp/isFirstDayOfMonth").default;
var DifferenceInMonths = require("date-fns/fp/differenceInMonths").default;
var DifferenceInMinutes = require("date-fns/fp/differenceInMinutes").default;
var DifferenceInSeconds = require("date-fns/fp/differenceInSeconds").default;
var FormatDistanceStrict = require("date-fns/fp/formatDistanceStrict").default;
var DifferenceInBusinessDays = require("date-fns/fp/differenceInBusinessDays").default;
var DifferenceInCalendarDays = require("date-fns/fp/differenceInCalendarDays").default;
var DifferenceInMilliseconds = require("date-fns/fp/differenceInMilliseconds").default;
var DifferenceInCalendarYears = require("date-fns/fp/differenceInCalendarYears").default;
var FormatDistanceWithOptions = require("date-fns/fp/formatDistanceWithOptions").default;
var DifferenceInCalendarMonths = require("date-fns/fp/differenceInCalendarMonths").default;
var ReasonDateFnsCurryHelpers$ReasonDateFns = require("./ReasonDateFnsCurryHelpers.bs.js");
var FormatDistanceStrictWithOptions = require("date-fns/fp/formatDistanceStrictWithOptions").default;

var Locales = {};

var partial_arg = ClosestIndexTo;

function closestIndexTo(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg, param, param$1);
}

var partial_arg$1 = FormatWithOptions;

function formatWithOptions(param, param$1, param$2) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry3(partial_arg$1, param, param$1, param$2);
}

var partial_arg$2 = Format;

function format(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$2, param, param$1);
}

var partial_arg$3 = ClosestTo;

function closestTo(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$3, param, param$1);
}

var partial_arg$4 = CompareAsc;

function compareAsc(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$4, param, param$1);
}

var partial_arg$5 = CompareDesc;

function compareDesc(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$5, param, param$1);
}

var partial_arg$6 = FormatDistance;

function formatDistance(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$6, param, param$1);
}

var partial_arg$7 = FormatDistanceWithOptions;

function formatDistanceWithOptions(param, param$1, param$2) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry3(partial_arg$7, param, param$1, param$2);
}

var partial_arg$8 = FormatDistanceStrict;

function formatDistanceStrict(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$8, param, param$1);
}

var partial_arg$9 = FormatDistanceStrictWithOptions;

function formatDistanceStrictWithOptions(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$9, param, param$1);
}

var partial_arg$10 = FormatRelative;

function formatRelative(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$10, param, param$1);
}

var partial_arg$11 = IsAfter;

function isAfter(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$11, param, param$1);
}

var partial_arg$12 = IsBefore;

function isBefore(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$12, param, param$1);
}

var partial_arg$13 = IsEqual;

function isEqual(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$13, param, param$1);
}

var partial_arg$14 = LightFormat;

function lightFormat(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$14, param, param$1);
}

var partial_arg$15 = Parse;

function parse(param, param$1, param$2) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry3(partial_arg$15, param, param$1, param$2);
}

var partial_arg$16 = AddBusinessDays;

function addBusinessDays(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$16, param, param$1);
}

var partial_arg$17 = AddDays;

function addDays(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$17, param, param$1);
}

var partial_arg$18 = DifferenceInBusinessDays;

function differenceInBusinessDays(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$18, param, param$1);
}

var partial_arg$19 = DifferenceInCalendarDays;

function differenceInCalendarDays(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$19, param, param$1);
}

var partial_arg$20 = DifferenceInDays;

function differenceInDays(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$20, param, param$1);
}

var partial_arg$21 = IsSameDay;

function isSameDay(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$21, param, param$1);
}

var partial_arg$22 = SetDayOfYear;

function setDayOfYear(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$22, param, param$1);
}

var partial_arg$23 = SubDays;

function subDays(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$23, param, param$1);
}

var partial_arg$24 = AddMilliseconds;

function addMilliseconds(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$24, param, param$1);
}

var partial_arg$25 = DifferenceInMilliseconds;

function differenceInMilliseconds(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$25, param, param$1);
}

var partial_arg$26 = SetMilliseconds;

function setMilliseconds(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$26, param, param$1);
}

var partial_arg$27 = SubMilliseconds;

function subMilliseconds(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$27, param, param$1);
}

var partial_arg$28 = AddSeconds;

function addSeconds(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$28, param, param$1);
}

var partial_arg$29 = DifferenceInSeconds;

function differenceInSeconds(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$29, param, param$1);
}

var partial_arg$30 = SetSeconds;

function setSeconds(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$30, param, param$1);
}

var partial_arg$31 = IsSameSecond;

function isSameSecond(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$31, param, param$1);
}

var partial_arg$32 = SubSeconds;

function subSeconds(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$32, param, param$1);
}

var partial_arg$33 = AddMinutes;

function addMinutes(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$33, param, param$1);
}

var partial_arg$34 = DifferenceInMinutes;

function differenceInMinutes(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$34, param, param$1);
}

var partial_arg$35 = SetMinutes;

function setMinutes(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$35, param, param$1);
}

var partial_arg$36 = IsSameMinute;

function isSameMinute(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$36, param, param$1);
}

var partial_arg$37 = SubMinutes;

function subMinutes(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$37, param, param$1);
}

var partial_arg$38 = AddHours;

function addHours(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$38, param, param$1);
}

var partial_arg$39 = DifferenceInHours;

function differenceInHours(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$39, param, param$1);
}

var partial_arg$40 = SetHours;

function setHours(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$40, param, param$1);
}

var partial_arg$41 = IsSameHour;

function isSameHour(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$41, param, param$1);
}

var partial_arg$42 = SubHours;

function subHours(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$42, param, param$1);
}

var partial_arg$43 = SetDay;

function setDay(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$43, param, param$1);
}

var partial_arg$44 = SetDay;

function setDayWithOptions(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$44, param, param$1);
}

var partial_arg$45 = SetISODay;

function setISODay(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$45, param, param$1);
}

var partial_arg$46 = AddWeeks;

function addWeeks(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$46, param, param$1);
}

var partial_arg$47 = DifferenceInWeeks;

function differenceInWeeks(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$47, param, param$1);
}

var partial_arg$48 = SetWeek;

function setWeek(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$48, param, param$1);
}

var partial_arg$49 = IsSameWeek;

function isSameWeek(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$49, param, param$1);
}

var partial_arg$50 = SubWeeks;

function subWeeks(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$50, param, param$1);
}

var partial_arg$51 = AddMonths;

function addMonths(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$51, param, param$1);
}

var partial_arg$52 = DifferenceInMonths;

function differenceInMonths(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$52, param, param$1);
}

var partial_arg$53 = DifferenceInCalendarMonths;

function differenceInCalendarMonths(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$53, param, param$1);
}

var partial_arg$54 = SetMonth;

function setMonth(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$54, param, param$1);
}

var partial_arg$55 = IsSameMonth;

function isSameMonth(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$55, param, param$1);
}

var partial_arg$56 = SubMonths;

function subMonths(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$56, param, param$1);
}

var partial_arg$57 = IsFirstDayOfMonth;

function isFirstDayOfMonth(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$57, param, param$1);
}

var partial_arg$58 = IsLastDayOfMonth;

function isLastDayOfMonth(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$58, param, param$1);
}

var partial_arg$59 = AddYears;

function addYears(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$59, param, param$1);
}

var partial_arg$60 = DifferenceInYears;

function differenceInYears(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$60, param, param$1);
}

var partial_arg$61 = DifferenceInCalendarYears;

function differenceInCalendarYears(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$61, param, param$1);
}

var partial_arg$62 = SetYear;

function setYear(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$62, param, param$1);
}

var partial_arg$63 = IsSameYear;

function isSameYear(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$63, param, param$1);
}

var partial_arg$64 = SubYears;

function subYears(param, param$1) {
  return ReasonDateFnsCurryHelpers$ReasonDateFns.curry2(partial_arg$64, param, param$1);
}

exports.Locales = Locales;
exports.closestIndexTo = closestIndexTo;
exports.formatWithOptions = formatWithOptions;
exports.format = format;
exports.closestTo = closestTo;
exports.compareAsc = compareAsc;
exports.compareDesc = compareDesc;
exports.formatDistance = formatDistance;
exports.formatDistanceWithOptions = formatDistanceWithOptions;
exports.formatDistanceStrict = formatDistanceStrict;
exports.formatDistanceStrictWithOptions = formatDistanceStrictWithOptions;
exports.formatRelative = formatRelative;
exports.isAfter = isAfter;
exports.isBefore = isBefore;
exports.isEqual = isEqual;
exports.lightFormat = lightFormat;
exports.parse = parse;
exports.addBusinessDays = addBusinessDays;
exports.addDays = addDays;
exports.differenceInBusinessDays = differenceInBusinessDays;
exports.differenceInCalendarDays = differenceInCalendarDays;
exports.differenceInDays = differenceInDays;
exports.isSameDay = isSameDay;
exports.setDayOfYear = setDayOfYear;
exports.subDays = subDays;
exports.addMilliseconds = addMilliseconds;
exports.differenceInMilliseconds = differenceInMilliseconds;
exports.setMilliseconds = setMilliseconds;
exports.subMilliseconds = subMilliseconds;
exports.addSeconds = addSeconds;
exports.differenceInSeconds = differenceInSeconds;
exports.setSeconds = setSeconds;
exports.isSameSecond = isSameSecond;
exports.subSeconds = subSeconds;
exports.addMinutes = addMinutes;
exports.differenceInMinutes = differenceInMinutes;
exports.setMinutes = setMinutes;
exports.isSameMinute = isSameMinute;
exports.subMinutes = subMinutes;
exports.addHours = addHours;
exports.differenceInHours = differenceInHours;
exports.setHours = setHours;
exports.isSameHour = isSameHour;
exports.subHours = subHours;
exports.setDay = setDay;
exports.setDayWithOptions = setDayWithOptions;
exports.setISODay = setISODay;
exports.addWeeks = addWeeks;
exports.differenceInWeeks = differenceInWeeks;
exports.setWeek = setWeek;
exports.isSameWeek = isSameWeek;
exports.subWeeks = subWeeks;
exports.addMonths = addMonths;
exports.differenceInMonths = differenceInMonths;
exports.differenceInCalendarMonths = differenceInCalendarMonths;
exports.setMonth = setMonth;
exports.isSameMonth = isSameMonth;
exports.subMonths = subMonths;
exports.isFirstDayOfMonth = isFirstDayOfMonth;
exports.isLastDayOfMonth = isLastDayOfMonth;
exports.addYears = addYears;
exports.differenceInYears = differenceInYears;
exports.differenceInCalendarYears = differenceInCalendarYears;
exports.setYear = setYear;
exports.isSameYear = isSameYear;
exports.subYears = subYears;
/* partial_arg Not a pure module */
