// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Max = require("date-fns/fp/max").default;
var Ru = require("date-fns/locale/ru").default;
var ParseISO = require("date-fns/fp/parseISO").default;
var DateFns$ReasonDateFns = require("./DateFns.bs.js");
var StartOfDay = require("date-fns/fp/startOfDay").default;

console.log(new Date());

console.log(DateFns$ReasonDateFns.isBefore(new Date(), new Date()));

console.log(Max([
          new Date(),
          new Date()
        ]));

DateFns$ReasonDateFns.lightFormat("yyyy-MM-dd", DateFns$ReasonDateFns.closestTo([
          ParseISO("2019-08-21T13:00:03.058Z"),
          new Date()
        ], DateFns$ReasonDateFns.addDays(-2, DateFns$ReasonDateFns.addDays(2, new Date()))));

DateFns$ReasonDateFns.formatWithOptions({
      locale: Ru
    }, "yyyy-MM-dd", new Date());

console.log(DateFns$ReasonDateFns.addMilliseconds(1000, DateFns$ReasonDateFns.addSeconds(10, DateFns$ReasonDateFns.addMinutes(10, new Date()))));

console.log("test", DateFns$ReasonDateFns.setHours(7, StartOfDay(DateFns$ReasonDateFns.addDays(1, new Date()))));

/*  Not a pure module */
