// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as Max from "date-fns/fp/max";
import * as ParseISO from "date-fns/fp/parseISO";
import * as DateFns$ReasonDateFns from "./DateFns.bs.js";

console.log(new Date());

console.log(DateFns$ReasonDateFns.isBefore(new Date(), new Date()));

console.log(Max.default(/* array */[
          new Date(),
          new Date()
        ]));

DateFns$ReasonDateFns.lightFormat("YYYY-MM-DD", DateFns$ReasonDateFns.closestTo(/* array */[
          ParseISO.default("2019-08-21T13:00:03.058Z"),
          new Date()
        ], DateFns$ReasonDateFns.addDays(-2, DateFns$ReasonDateFns.addDays(2, new Date()))));

export {
  
}
/*  Not a pure module */
